export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const GOT_EMPLOYEES = "GOT_EMPLOYEES";

export const GET_EMPLOYEE = "GET_EMPLOYEE";
export const GOT_EMPLOYEE = "GOT_EMPLOYEE";

export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const ADDED_EMPLOYEE = "ADDED_EMPLOYEE";

export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const UPDATED_EMPLOYEE = "UPDATED_EMPLOYEE";

export const DELETE_EMPLOYEE = "DELETE_POST";
export const DELETED_EMPLOYEE = "DELETED_POST";
